config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  #get 'pages/home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, allow_destroy: true, reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader


  def self.angular
    where(subtitle: "Angular") #Portfolio.where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  layout 'portfolio'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all


  def index
    #@portfolio_items = Portfolio.where(subtitle: "Angular")
    #@portfolio_items = Portfolio.angular   We are using the model class definition.
    #@portfolio_items = Portfolio.ruby_on_rails_portfolio_items We are using custom scope.
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order]. each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    #@portfolio_item = Portfolio.find(params[:id])
  end

  def update
    #@portfolio_item = Portfolio.find(params[:id])

    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end

  end

  def show
    #@portfolio_item = Portfolio.find(params[:id])
  end

  def destroy
    # Perform the lookup
    #@portfolio_item = Portfolio.find(params[:id])
    #Destroys the record
    @portfolio_item.destroy
    #Redirects

    respond_to do |format|
        format.html { redirect_to portfolios_path, notice: 'Portfolio was removed.' }
    end
  end

  private

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end



  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                      )
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}x#{width}.jpg"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    else
      image_generator(height: '600', width: '400')
    end
  end


  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end
end

app/views/portfolios/_form.html.erb
<%= simple_form_for @portfolio_item do |f| %>
 <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <%=  f.input :title %>
      <%=  f.input :subtitle %>
      <%=  f.input :main_image, as: :file %>
      <%=  f.input :thumb_image, as: :file %>
    </div>
    <div class="col-md-6">
      <%=  f.input :body, :input_html => {:rows => 14} %>
    </div>
    <div class="col-md-12">
      <h3>Technologies used</h3>
      <div>
        <%= f.simple_fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies %>
        </div>
      </div>
    </div>
    <%= f.submit "Submit Portfolio", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-auto">
  <a href="<%= portfolio_show_path(portfolio_item) %>", class="card-capture">
    <div class="card mb-4 shadow-sm index-card" data-id="<%= portfolio_item.id %>">
      <img src=<%= portfolio_img(portfolio_item.thumb_image, 'thumb')%> alt="" class="portfolio-responsive">
      <div class="card-body">
        <h5 class="card-header-portfolio">
          <%= portfolio_item.title %>
        </h5>
        <p class="card-text">
          <%= portfolio_item.subtitle %>
        </p>
        <div class="d-flex justify-content-between align-items-center">
          <div class="btn-group">
          </div>
        </div>
      </div>
    </div>
  </a>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="nested-fields">
  <%= f.input :name %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light" id="background">
  <%= source_helper("alert-success") %>
  <div class="container">
    <div class="row justify-content-center <%= "sortable" if logged_in?(:site_admin)%>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new portfolio item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container portfolio-show-container">
  <div class="card show-card">
    <div class="row">
      <div class="col-md-8 show-img-min">
        <img src=<%= portfolio_img(@portfolio_item.main_image, 'main')%> alt="" width="100%">
      </div>
      <div class="col-md-4 show-font-min">
        <div class="title-separation">
          <h3> <%= @portfolio_item.title %></h3>
          <h6> <%= @portfolio_item.subtitle %></h6>
        </div>
        <h5>Technologies Used</h5>
        <% @portfolio_item.technologies.each do |technology_item| %>
          <ul>
            <li><%= technology_item.name %></li>
          </ul>
        <% end %>
        <% if logged_in?(:site_admin) %>
          <div>
            <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-danger' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 show-font-min">
        <div class="portfolio-content-body">
          <h5>Read more about <%= @portfolio_item.title %></h5>
          <p> <%= markdown @portfolio_item.body %></p>
        </div>
      </div>
    </div>
  </div>
</div>