config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  #get 'pages/home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "Jeff Monteiro Portfolio", sticky: false) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "Jeff Monteiro Portfolio", sticky: false) %>
<% else flash[:notice] %>
  <%= js add_gritter(flash[:notice], title: "Jeff Monteiro Portfolio", sticky: false) %>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead mb-auto">
  <div class="inner">
    <h3 class="masthead-brand">Jeffrey Xavier Monteiro</h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper "nav-link", "span" %>
      <%= login_helper "nav-link" %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p><a href="#">Back to top</a></p>
</footer>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light blog-nav">
  <div class="container">
    <a class="navbar-brand" href="#">Jeffrey Xavier Monteiro Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <%= nav_helper "nav-item nav-link", "span" %>
        <%= login_helper "nav-item nav-link" %>
      </div>
    </div>

  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">Why the Blog?</h4>
    <p class="mb-0">I think it's always important to remember your roots and where you came from. Wherever the journey leads, this blog will function as a roadmap to where it all began. Enjoy the ride!</p>
  </div>


  <%= source_helper("alert-success") %>





  <div class="p-4">
    <h4>Topics</h4>
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
    <% end %>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Follow Me</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/jeffreyxmonteiro/" target="_blank"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.linkedin.com/in/jeffrey-monteiro/" target="_blank"><%= fa_icon "linkedin" %></a></li>
      <li><a href="https://www.instagram.com/chamonejefe/" target="_blank"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <%= link_to "Home", root_path %>
  <%= link_to "Portfolio", portfolios_path %>
  <%= link_to "About Me", about_path %>
  <%= link_to "Contact", contact_path %>
  <%= link_to "Blogs", blogs_path %>
</div>

app/views/shared/_portfolio_banner.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">APEX Products</h1>
    <p class="lead">Darwinism aside, below are some projects and products I have had the great pleasure of participating in - I can proudly say that each one has profoundly impacted my personal and professional development.</p>
    <div class="portfolio-buttons">
      <%= link_to "Learn More About Me", about_path, class: "port-btn btn btn-success my-2" %>
    </div>
  </div>
</section>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-lighted">
  <div class="container">
    <p class="float-right">
      <%= link_to "All Portfolio Items", portfolios_path %> /
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">Thanks!</h4>
          <p class="text-muted">I appreciate you taking the time to visit my portfolio. Please let me know if you have questions about any of these projects.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper "text-white", "li" %>
            <li><%= login_helper "text-white" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Jeffrey Xavier Monteiro Portfolio</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>